In [3]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
path='C:Copy the path of csv file here'
song_data= pd.read_csv(path)
song_data.head(10)

song_id                                              title  \
0  SOQMMHC12AB0180CB8                                       Silent Night   
1  SOVFVAK12A8C1350D9                                        Tanssi vaan   
2  SOGTUKN12AB017F4F1                                  No One Could Ever   
3  SOBNYVR12A8C13558C                                      Si Vos Querés   
4  SOHSBXH12A8C13B0DF                                   Tangle Of Aspens   
5  SOZVAPQ12A8C13B63C  Symphony No. 1 G minor "Sinfonie Serieuse"/All...   
6  SOQVRHI12A6D4FB2D7                                   We Have Got Love   
7  SOEYRFT12AB018936C                                  2 Da Beat Ch'yall   
8  SOPMIYT12A6D4F851E                                            Goodbye   
9  SOJCFMH12A8C13B0C2                         Mama_ mama can't you see ?   

                                release  \
0                 Monster Ballads X-Mas   
1                           Karkuteillä   
2                                Butter   
3                               De Culo   
4  Rene Ablaze Presents Winter Sessions   
5      Berwald: Symphonies Nos. 1/2/3/4   
6             Strictly The Best Vol. 34   
7                               Da Bomb   
8                             Danny Boy   
9  March to cadence with the US marines   

                                      artist_name  year  
0                                Faster Pussy cat  2003  
1                                Karkkiautomaatti  1995  
2                                  Hudson Mohawke  2006  
3                                     Yerba Brava  2003  
4                                      Der Mystic     0  
5                                David Montgomery     0  
6                              Sasha / Turbulence     0  
7                                      Kris Kross  1993  
8                                    Joseph Locke     0  
9  The Sun Harbor's Chorus-Documentary Recordings     0

In [36]:
df = song_data.sample(5000).reset_index(drop=True)
df.shape

(5000, 5)

In [37]:
selected_features = ['title','artist_name']
print(selected_features)

['title', 'artist_name']


In [38]:
for f in selected_features:
    df[f]=df[f].fillna('')

In [18]:
combine_features = df['title']+''+df['artist_name']
combine_features = combine_features.fillna('')
print(combine_features)

0                             Maha lo E DerekHenry Kaiser
1                  Cellar Door (Album Version)Holly Brook
2                  Little LiarJoan Jett & The Blackhearts
3                                    The SwingHans Zimmer
4                                TechnocarL'Ensemble Rayé
                              ...                        
4995    When Machines Exceed Human IntelligenceHarmoni...
4996           ValerieMark Ronson featuring Amy Winehouse
4997                 You Got Us All WrongMersonary Killaz
4998                          Get Your Hopes UpHard Place
4999                          Call Me A FreakCarla Lavern
Length: 5000, dtype: object


In [39]:
vectorizer = TfidfVectorizer()
f_vectors = vectorizer.fit_transform(combine_features)
print(f_vectors)


# tfidf_vectorizer = TfidfVectorizer()
# tfidf_matrix = tfidf_vectorizer.fit_transform(combine_features)
# tfidf_matrix_csr = csr_matrix(tfidf_matrix)
# print(tfidf_matrix_csr)

  (0, 5174)	0.5152653366193549
  (0, 2591)	0.5152653366193549
  (0, 5782)	0.451115172251642
  (0, 6051)	0.5152653366193549
  (1, 1492)	0.4860094770678051
  (1, 4546)	0.43709565025813246
  (1, 10771)	0.21679287349629067
  (1, 356)	0.24047300122113713
  (1, 2821)	0.45651992297001215
  (1, 1785)	0.5094166529885664
  (2, 1172)	0.5317858083546971
  (2, 10080)	0.17404470887113388
  (2, 5042)	0.5317858083546971
  (2, 5656)	0.5317858083546971
  (2, 5755)	0.3483102085951345
  (3, 11512)	0.6888996034187869
  (3, 9883)	0.6888996034187869
  (3, 10080)	0.22546545815019264
  (4, 8186)	0.5972830538518106
  (4, 3173)	0.5352624656772698
  (4, 10009)	0.5972830538518106
  (5, 302)	0.5030583909405097
  (5, 10232)	0.5968190182463557
  (5, 7210)	0.25792973069579694
  (5, 11062)	0.5693957927373497
  :	:
  (4995, 3293)	0.43853885262415104
  (4995, 6012)	0.43853885262415104
  (4995, 123)	0.41838843937942993
  (4995, 11099)	0.31716144908051414
  (4995, 4654)	0.3839410804121812
  (4996, 493)	0.47923194671216585


In [40]:
similarity = cosine_similarity(f_vectors)
print(similarity)

# n_components = 3
# svd = TruncatedSVD(n_components=n_components)
# tfidf_matrix_svd = svd.fit_transform(tfidf_matrix)

# similarity_svd = cosine_similarity(tfidf_matrix_svd)


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [41]:
df.head(10)

song_id                      title  \
0  SOWAOIP12AB017C099               Puntualísimo   
1  SOQLTHY12A81C215F0         Let's Fall In Love   
2  SOYWGAP12A8C13321B            I Wanna Go Back   
3  SOPSSNQ12AB0189D2A                   Sweatbox   
4  SOQYEIX12A6D4F92A8               Lord of lies   
5  SOYLKCX12AB01815D5      Go Thru Life With You   
6  SOFKLTD12A8C130F75                   Thin Air   
7  SORTATL12A6D4F6135  Be Joyful (Album Version)   
8  SOQFMEK12AB017DBEA                       Yuki   
9  SOYCEQF12AC3DF5F72        Pop Bottles (Remix)   

                           release      artist_name  year  
0                           Status    Chico Y Chica     0  
1     The Very Best Of Diana Krall      Diana Krall  1999  
2                       Super Hits      Eddie Money  1986  
3                808 State Of Mind         Shameboy  2010  
4                            Awake        CREMATORY     0  
5  Chris Kenner Selected Favorites     Chris Kenner     0  
6    Looney Tunes / Back In Action  Jerry Goldsmith  2003  
7              Rootical Vibrations      Tena Stelin     0  
8                             Yuki  Hideo Kobayashi     0  
9                        Legendary        Rick Ross     0

In [43]:
def recomandation(title):
    idx=df[df['title'] == title].index[0]
    d= sorted(list(enumerate(similarity[idx])),reverse=False,key=lambda x:x[1])
    title = []
    for i in d[1:21]:
        title.append(df.iloc[i[0]].title)
    return title

In [46]:
recomandation('Sweatbox')

["Let's Fall In Love",
 'Lord of lies',
 'Go Thru Life With You',
 'Thin Air',
 'Be Joyful (Album Version)',
 'Yuki',
 'Pop Bottles (Remix)',
 'Life I Live',
 'New Beginning (Mamba Seyra)',
 'Everybody Makes Mistakes',
 'Zea',
 'Nada Contigo',
 'De Noche - Original',
 'Junto A Ti',
 'Square Root Of Me',
 'I Have You To Thank',
 'Stay Away From My Window!',
 'True Love',
 'Rukun Kita',
 'Romance']